import re
f = open('dashboard.html', 'r', encoding='utf-8')
content = f.read()
f.close()
target = '      </form>\n\n      <!-- Class Performance Overview (Advanced Analytics) -->'
replacement = '''        <div class="form-group" style="margin-bottom: 1.5rem; margin-top: 1rem;"><label>Groups taking this exam (leave all unchecked to allow everyone)</label><div style="display: flex; gap: 1rem; flex-wrap: wrap;" id="exam-groups-container"><label style="display: flex; align-items: center; gap: 0.25rem;"><input type="checkbox" value="Ignite"> Ignite</label><label style="display: flex; align-items: center; gap: 0.25rem;"><input type="checkbox" value="Velocity"> Velocity</label><label style="display: flex; align-items: center; gap: 0.25rem;"><input type="checkbox" value="Group 3"> Group 3</label><label style="display: flex; align-items: center; gap: 0.25rem;"><input type="checkbox" value="Group 4"> Group 4</label><label style="display: flex; align-items: center; gap: 0.25rem;"><input type="checkbox" value="Group 5"> Group 5</label></div></div>      </form>\n\n      <!-- Student Groups Management -->\n      <div class="panel-header" style="margin-top: 3rem;"><div><h1>Student Groups Management</h1><p class="subtitle">Assign students to specific groups.</p></div></div><div class="submit-card wide-card" style="margin-bottom: 3rem;"><div class="form-row"><div class="form-group" style="flex: 1.5;"><label for="manage-group-student">Select Student</label><select id="manage-group-student"><option value="">Select Student...</option></select></div><div class="form-group" style="flex: 1;"><label for="manage-group-select">Select Group</label><select id="manage-group-select"><option value="">-- No Group --</option><option value="Ignite">Ignite</option><option value="Velocity">Velocity</option><option value="Group 3">Group 3</option><option value="Group 4">Group 4</option><option value="Group 5">Group 5</option></select></div></div><button class="btn btn-primary" id="manage-group-update-btn">Update Group</button><p id="manage-group-status" style="margin-top: 1rem; font-size: 0.9rem; font-weight: 500; display: none;"></p></div>\n\n      <!-- Class Performance Overview (Advanced Analytics) -->'''
content = content.replace(target, replacement)
f = open('dashboard.html', 'w', encoding='utf-8')
f.write(content)
f.close()
